### ISSUE TITLE
Add the ability to show the QR outside the terminal

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/qrcp#140]
Even though this is a command line application, many users are running into rendering issues that may be caused by the terminal font (see https://github.com/claudiodangelis/qrcp/issues/126, https://github.com/claudiodangelis/qrcp/issues/99, https://github.com/claudiodangelis/qrcp/issues/7, https://github.com/claudiodangelis/qrcp/issues/6), would be nice to have the ability to print the QR somewhere else, for example by automatically opening a browser window or an user-defined program.

**Comment by barthr** [comment]
I think this can be done quite easily. 

Instead of having `RenderString` print directly to the stdout the function need to be adjusted a bit (in a backwards compatible fashion)

```
func RenderString(s string) {
	q, err := qrcode.New(s, qrcode.Medium)
	if err != nil {
		panic(err)
	}
	fmt.Println(q.ToSmallString(false))
}
```
Possible solution
```
func RenderString(s string, out ...io.Writer) {
	q, err := qrcode.New(s, qrcode.Medium)
	if err != nil {
		panic(err)
	}

	var writer io.Writer = os.Stdout
	if len(out) > 0 {
		writer = out[0]
	}
	io.Copy(writer, strings.NewReader(q.ToSmallString(false)))
}
```

Though the name `RenderString` doesn't really cover it anymore, this way we you can pass any output writer (which can be a file, or even a `http.ResponseWriter`.

**Comment by claudiodangelis** [comment]
Props to @camgraff for implementing this feature! You can now pass the `--browser` flag and have a QR printed to your default browser.
