### ISSUE TITLE
windows prompts me that this application cannot run on your computer

### ISSUE THREAD

**Issue by lzq-dingyuan** [claudiodangelis/qrcp#158]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [ true ] I have a question
- [ ] Other

When I download your software, windows prompts me that this application cannot run on your computer，I downloaded the windows version of the software from your website. (https://github.com/claudiodangelis/qrcp/releases   qrcp_0.6.3_Windows_i386.tar.gz && qrcp_0.6.3_Windows_x86_64.tar.gz
)

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

**Comment by claudiodangelis** [comment]
Hello @lzq-dingyuan, sorry to hear you're running into troubles. Unfortunately I am not too much familiar with Windows, so I have no idea how could I start investigating this.

Could you please let me know if your issue is somewhat related to the scenario described in this StackOverflow post? https://stackoverflow.com/questions/26951762/i-cant-run-go-programs-anymore

Thanks,
C

**Comment by lzq-dingyuan** [comment]
thank you for your reply! I will try it.

**Comment by claudiodangelis** [comment]
Hello @lzq-dingyuan, did you have any success with this?
Thank you,
Claudio
