### ISSUE TITLE
Unable to open URL when set interface to "any"

### ISSUE THREAD

**Issue by S96EA** [claudiodangelis/qrcp#168]
When I send a file by set interface to "any", I cannot open the URL in another computer.
`qrcp -i any xxx.pdf`

**Comment by claudiodangelis** [comment]
Hi, in order to open the URL you must make sure that the other computer can reach the computer where qrcp is running through the external IP on the given port. If the computer when qrcp is running is a home computer connected to a router, you will have to set a port forwarding rule.

Can you please provide more information about the computers involved? For example, they are two home computers connected to the same router, etc.

Thanks,
Claudio

**Comment by S96EA** [comment]
These two computers are not in the same LAN. So I need to configure port forwarding rule? How should I do it?

Thanks！

**Comment by claudiodangelis** [comment]
First of all, please note that every router has its own admin dashboard, so refer to the manual if you can't find the port forwarding settings. Let's say that this is your scenario:
- Your router IP: `192.168.1.1`
- Your computer IP: `192.168.1.5`
- Router's external IP is: `100.200.10.50`
- The port you want to forward: `18080`

The concept of port forwarding is simple: the traffic to `192.168.1.1:18080` should be _forwarded_ to `192.168.1.5:18080`. Which means that the traffic to `100.200.10.50:18080` is _forwarded_ to `192.168.1.5:18080`.

Here's the full workflow:

1. Take note of your local computer IP (I will assume is `192.168.1.5)`
2. Go to your router's admin console (usually http://192.168.0.1 or http://192.168.1.1, I will assume the latter)
3. Go to port forwarding settings, and set forwarding from `192.168.1.1` to `192.168.1.5` on port `18080`
4. Run `qrcp -i any -p 18080 xxx.pdf`
5. Open the URL from any computer

Note that you have to specify the port in `qrcp` because you did not forward _all_ ports but just a specific one.

Please let me know if this helps and it works, thanks!

Claudio

**Comment by S96EA** [comment]
Thank you so much !!

**Comment by claudiodangelis** [comment]
Did it work? Can I close this issue?
