### ISSUE TITLE
qrcp should allow files in shell completion

### ISSUE THREAD

**Issue by nikitabobko** [claudiodangelis/qrcp#261]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: `go version go1.19.3 linux/amd64`
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to empty string
- My `qrcp version` output is: `qrcp 0.9.1 [date: 2022-03-14T15:44:28Z]`

Steps to reproduce:
1. type `qrcp file-prefix-`
2. Press `<Tab>`
Expected: Shell completion suggests file that I'm trying to type
Actual: Shell completion suggests nothing

Or if for some reason you don't like to complete file names together with `qrcp` commands (`send`, `receive`, `config`, ...) then at least it's expected to have file completion for `qrcp send <Tab>`

**Comment by claudiodangelis** [comment]
Hello @nikitabobko , apologies for the super late reply. This is very nice suggestion, I will try to have a look at this as soon as possible.

Thanks for your patience!
C

**Comment by fritzrehde** [comment]
I would also find this feature super useful!

**Comment by claudiodangelis** [comment]
Hello, it turns out this feature is already available.
Please refer to the shell completion section of the README: https://github.com/claudiodangelis/qrcp#shell-completion-scripts

Let me know if this helps, I will close this issue for now but please feel free to reopen it if you need additional clarification. Thanks!
C
