### ISSUE TITLE
"Can't connect to the server"

### ISSUE THREAD

**Issue by effeottantuno** [claudiodangelis/qrcp#286]
Hi, i've recently got a new pc and now qrcp won't work, when i scan the qr code on both my iphone using ios and my android using firefox i get this: 

![photo_2023-08-07_01-20-51](https://github.com/claudiodangelis/qrcp/assets/74515415/484ed4cc-0826-4643-b66d-a59d0a8ed8ae)
![photo_2023-08-07_01-20-46](https://github.com/claudiodangelis/qrcp/assets/74515415/68aa4bcf-0918-4a13-991e-36463f852051)

**Comment by effeottantuno** [comment]
i've also tried with the --keep-alive tag but still nohing.

**Comment by effeottantuno** [comment]
i've also tried using the --keep-alive tag but still nothing.

**Comment by claudiodangelis** [comment]
Hello @effeottantuno , try to pass the port number using standard ports, for example:

```
qrcp --port 8080 yourfile
```

And let me know if it works this way, it might be a firewall issue.

Thanks!
Claudio

**Comment by basketshoe** [comment]
@claudiodangelis I'm having the same issue, even with port 8080.
Tried with iOS 16.7.1 Safari and DuckDuckGo

**Comment by effeottantuno** [comment]
@claudiodangelis same as @basketshoe not working even with 8080, tried on android 14 using firefox

**Comment by claudiodangelis** [comment]
Please reach out to my email (my github username + gmail.com) or through Telegram (same github username), we can debug together privately.
Thanks!

**Comment by claudiodangelis** [comment]
After some debugging with @basketshoe and @effeottantuno it turned out that issue was caused by `firewalld` blocking incoming connections.

To permanently open a specific port run the following command, replacing 8080 with your preferred choice:
```
sudo firewall-cmd --permanent --add-port 8080
sudo firewall-cmd --reload
```
Run the tool using that port:
```
qrcp -p 8080
```

Remember that you can permanently configure the tool to use a specific port by adding this to the configuration file:
```
port: 8080
```

Also, read the documentation of firewalld for understanding the consequences of opening ports and to find right configuration for your needs: https://firewalld.org/
