### ISSUE TITLE
Implement as drag-and-drop desktop app

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/qrcp#35]
Not all users are tech-savvy enough to use command-line tools, what about bringing the concept of "scan & transfer" to regular desktop apps?

There might be a couple of usages, for example:

1. User launches the app, the main window is just a panel through which they can drag and drop the file(s) onto, or click a good old "Select file(s)" button
2. User drags the file(s) onto the app icon itself (I think many mac apps work this way)

Afterwards, a QR code is displayed and users can scan & download.

What do you think? Please share your ideas on this, thank you!

**Comment by FrontMage** [comment]
I think if the user is on Mac or Windows, many im clients have this file transporter which allows you simply transfer files or other stuff to your phone.
Which skips the scan part, because users have native apps installed both on pc and phone.
---
However, I suppose there is a need for transferring files from remote server to local, I'm preparing to fork and make a version works on a remote server.

**Comment by evilsocket** [comment]
Q: what's your plan of implementing cross platform d&d support? if you found a framework or something that makes that "easy", then i definitely think this is a great feature to implement, otherwise it might be quite complicated to implement (and support across os updates) from scratch. In this second case, the question is: is it worth it? m2c

**Comment by aust-n** [comment]
I think a drag and drop functionality _should_ be implemented simply as it adds to the app experience. You hit the nail on the head when you said that command-line execution of the app can be tedious for the non-tech-savvy. The functionality adds accessibility and ease of use to the app _however_, it might be fairly difficult to implement,

**Comment by claudiodangelis** [comment]
I'm bookmarking this QML frontend + Golang backend project (a popular clone of Sublime Text), it looks like a good approach: https://github.com/limetext/lime

**Comment by evilsocket** [comment]
yeah i was looking at this webview and looks simple and promising :D

**Comment by hellozee** [comment]
What about using [andlabs/ui](https://github.com/andlabs/ui) , we do need to package the c library but we can avoid webview this way.

**Comment by claudiodangelis** [comment]
Another GUI library I just came across: https://github.com/fyne-io/fyne

**Comment by CheatCoder** [comment]
> What about using [andlabs/ui](https://github.com/andlabs/ui) , we do need to package the c library but we can avoid webview this way.

The only Problem is this has no image Support(only in tables), how would you Show the qr-code in this libary?

When we need Image then i prefere fyne as a Desktop app.

**Comment by pearl2201** [comment]
I just clone to c# and add simple graphic ui.

https://github.com/pearl2201/qrcp

**Comment by michal037** [comment]
Maybe via light API, for example `qrcp --api`. Then qrcp will print an easily parseable text (process pipeline) that could be handled by additional GUI applications. This will allow GUI to be independent of core program.

---

@FrontMage

> However, I suppose there is a need for transferring files from remote server to local, I'm preparing to fork and make a version works on a remote server.

Check it out: https://github.com/schollz/croc
Add QR support and it's ready.

**Comment by Naheel-Azawy** [comment]
In case anyone lands here in the future, here's my wrapper
https://github.com/Naheel-Azawy/qrcp-win-ui

**Comment by faveoled** [comment]
Here's my take in Flutter:
https://github.com/faveoled/qrshare
